# https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  # Maintain dependencies for yarn
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    labels:
      - 'dependencies'
      - 'Dev/QA Attention'
    reviewers:
      - 'MilanVojnovic95'
      - 'wixzi'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
